# Generated by Django 5.1.4 on 2025-01-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIServer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowers',
            name='id',
        ),
        migrations.AlterField(
            model_name='flowers',
            name='flower_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
