# Generated by Django 5.1.4 on 2025-01-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIServer', '0002_remove_flowers_id_alter_flowers_flower_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='flower_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
