# Generated by Django 5.1.4 on 2025-01-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIServer', '0003_alter_flowers_flower_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
